//•	En cuanto a los estudiantes, se requiere almacenar el curso en el que están matriculados
//•	Por cada persona, se debe conocer, al menos, su nombre y 
//apellidos, su número de identificación y su estado civil

class ESTUDIANTE{

public string nombre;
public int cedula;
public int estadoCivil;


public void ESTUDIANTE (string nombre, int cedula, int estadoCivil)

public void  EscribeNombre (string nom)
{
    this.nombre=nom;
}
public void EscribeCedula (int cedu)
{
    this.cedula=cedu;
}

public void EscribeCivil( int civil)
{
    this.estadoCivil=civil;
}
{

console.writeLine("Ecribe nombre del estudiante:" +e1);
console.writeLine("Escribe cedula del estudiante:"+c1);
console.writeLine("Ecribe estado civil del estudiante;"+ec1);
}

return 0;

}