//Con respecto a los empleados, sean del tipo que sean, hay que saber su año de incorporación 
//a  la facultad y qué número de despacho tienen asignado. 
class PROFESORES {

public string nombre;
public int cedula;
public int estadoCivil;




public void PROFESORES(string nombre, int cedula, int estadoCivil)

public void  EscribeNombre (string nom)
{
    this.nombre=nom;
}
public void EscribeCedula (int cedu)
{
    this.cedula=cedu;
}

public void EscribeCivil( int civil)
{
    this.estadoCivil=civil;
}
{

console.writeLine("Ecribe nombre del profesor:" +p2);
console.writeLine("Escribe cedula del profesor:"+c2);
console.writeLine("Ecribe estado civil del profesor;"+ec2);
}

return 0;

}







}